### ISSUE TITLE
JoSS Review: State of the field

### ISSUE THREAD

**Issue by betteridiot** [babinyurii/RECAN#10]
In conjunction with the review of your package to JoSS (available at https://github.com/openjournals/joss-reviews/issues/2014), here is an issue for you to address for your submission.

While `recan` allows the plotting of genetic distances (much like RDP4 and RAT), and it does so interactively and ad hoc, it foregoes the ability to detect potential recombination events. This is one of the primary reasons others use those programs. 

Are there any future plans to implement potential recombination event detection into `recan`?

**Comment by ghost** [comment]
I agree with the comment of @betteridiot above. I also think this is the biggest weakness of the `recan`. While the package offers a very good visualisation tool for analysing genetic similarity, I would not call it a recombination detection tool since the detection requires completely manual assessment of the similarity plots.

In modern contexts, where we often have to work with a lot of data at once, I think it would be extremely helpful if `recan` can incorporate a method to detect potential recombination events.

**Comment by babinyurii** [comment]
I'm going to add a function which will go through the alignment and predict recombination break points based on genetic distance change. However, I need to collect and analyze more information on the confirmed recombination cases to set reasonable distance change parameters that seem to be different for RNA and DNA viruses.
Maybe it'll be better now to rename the paper to "Recan: Python tool for **analysis** of recombination events in viral genomes", as the package has no this function.

**Comment by babinyurii** [comment]
I'd like to proceed the review process with renaming the article to "Recan: Python tool for **analysis** of recombination events in viral genomes".
https://github.com/babinyurii/recan/blob/master/paper/paper.md

**Comment by ghost** [comment]
I understand that developing a method for recombination detection is not easy and will take some time. Perhaps, you may want to consider incorporating a currently existing method into your package.

For the moment, I think changing the title of the paper is good enough.

**Comment by betteridiot** [comment]
I agree with @lamhm
